# 텍스트 분석 - Bag of words
1. Count Vectorizer

In [47]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['You know I want your love. Because I love you.']

In [48]:
count_vect = CountVectorizer()
count_vect.fit(corpus)
output = count_vect.transform(corpus)
output.toarray()

array([[1, 1, 2, 1, 2, 1]], dtype=int64)

In [49]:
count_vect.vocabulary_

{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}

### 불용어 제거한 BoW

In [50]:
# CountVectorizer의 파라미터 불용어 제거
text = ["Family is not an important thing. It's everything"]
cvect = CountVectorizer(stop_words = ['the','a','an','is','not'])
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}


In [51]:
# sklearn에서 제공하는 불용어 제거
text = ["Family is not an important thing. It's everything"]
cvect = CountVectorizer(stop_words ='english')
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}


In [52]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\wontae\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [53]:
# NLTK에서 제공하는 불용어 사용
from nltk.corpus import stopwords
sw = stopwords.words('english')
len(sw)

179

In [54]:
text = ["Family is not an important thing. It's everything"]
cvect = CountVectorizer(stop_words = sw)
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


In [55]:
def get_word(index, voca):
    for key, value in voca.items():
        if value == index:
            return key

In [56]:
get_word(3, cvect.vocabulary_)

'thing'

### N-gram

In [57]:
# Maching is boring and learning is not fun. 
# 단어 순서 바뀌면 완전 다른 뜻이 되는데 이걸 못 잡는 BOW를 보완함
text = ["Machine learning is fun and is not boring."]
cvect = CountVectorizer(stop_words = sw)
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1]]
{'machine': 3, 'learning': 2, 'fun': 1, 'boring': 0}


In [58]:
# ngram_range = ( 시작, 끝 )
# ngram_range = (1,2): unigram부터 bigram까지
cvect = CountVectorizer(ngram_range = (1,2))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 2 1 1 1 1 1 1 1 1]]
{'machine': 10, 'learning': 8, 'is': 5, 'fun': 3, 'and': 0, 'not': 12, 'boring': 2, 'machine learning': 11, 'learning is': 9, 'is fun': 6, 'fun and': 4, 'and is': 1, 'is not': 7, 'not boring': 13}


In [59]:
cvect = CountVectorizer(ngram_range = (2,3))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1 1 1 1 1 1 1]]
{'machine learning': 10, 'learning is': 8, 'is fun': 4, 'fun and': 2, 'and is': 0, 'is not': 6, 'not boring': 12, 'machine learning is': 11, 'learning is fun': 9, 'is fun and': 5, 'fun and is': 3, 'and is not': 1, 'is not boring': 7}


In [60]:
cvect = CountVectorizer(ngram_range = (2,3), stop_words = 'english')
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1]]
{'machine learning': 3, 'learning fun': 1, 'fun boring': 0, 'machine learning fun': 4, 'learning fun boring': 2}


In [61]:
cvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (2, 3),
 'preprocessor': None,
 'stop_words': 'english',
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

2. TF-IDF

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do'
]
cvect = CountVectorizer()
print(cvect.fit_transform(corpus).toarray())
print(cvect.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [63]:
# 사용법은 Cvect와 똑같다
tfidf_vect = TfidfVectorizer()
print(tfidf_vect.fit_transform(corpus).toarray())
print(tfidf_vect.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}
